openapi: 3.0.0
info:
  title: Bulk upload API
  version: 1.0.0
  description: API for uploading bulk participant data
tags:
  - name: "Upload"
paths:
  '/{state}/upload/{filename}':
    $ref: './upload.yaml'
security:
  - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Ocp-Apim-Subscription-Key
