# Orchestrator API base spec
openapi: 3.0.0
info:
  title: "Active Matching API"
  version: 1.0.0
  description: "API for detecting matching PII records across all participating states."
tags:
  - name: "Match"
servers:
  - url: "/v1"
paths:
  /query:
    $ref: './query.yaml'
