version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.1.0

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:3.1
    steps:
      - checkout
      - run:
          name: Install zip
          command: |
            apt-get update -y
            apt-get install -y zip
      - run:
          working_directory: dashboard/app
          name: Build .NET project
          command: dotnet publish -o ./build
      - run:
          working_directory: dashboard/app/build
          name: Zip project build
          command: zip -r build.zip .
