version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.1.0

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:3.1
    steps:
      - checkout
      - run:
          name: Install zip
          command: |
            apt-get update -y
            apt-get install -y zip
      - run:
          working_directory: dashboard/app
          name: Build .NET project
          command: dotnet publish -o ./build
      - run:
          working_directory: dashboard/app/build
          name: Zip project build
          command: zip -r build.zip .
  deploy:
    executor: azure-cli/azure-docker
    steps:
      - checkout
      - azure-cli/login-with-service-principal
      - run:
          name: Upload app
          working_directory: dashboard/app
          command: az webapp deployment source config-zip -g $AZURE_RESOURCE_GROUP -n $APP_NAME --src ./build.zip

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build