version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.1.0

jobs:
  test:
    environment:
      MSBUILD_PROPS: "-p:ContinuousIntegrationBuild=true"
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:3.1
    steps:
      - checkout
      - run:
          name: Setup Code Climate reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
      - run:
          working_directory: dashboard/tests/Piipan.Dashboard.Tests
          name: Test Dashboard
          command: dotnet test $MSBUILD_PROPS --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=lcov
      - run:
          working_directory: etl/tests/Piipan.Etl.Tests
          name: Test Etl
          command: dotnet test $MSBUILD_PROPS --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=lcov
      - run:
          name: Upload Code Climate coverage report
          command: |
            ./cc-test-reporter -d format-coverage ./dashboard/tests/Piipan.Dashboard.Tests/TestResults/**/coverage.info --input-type lcov -p /root/project -o /tmp/codeclimate.dashboard.json 
            ./cc-test-reporter -d format-coverage ./etl/tests/Piipan.Etl.Tests/TestResults/**/coverage.info --input-type lcov -p /root/project -o /tmp/codeclimate.etl.json
            ./cc-test-reporter sum-coverage /tmp/codeclimate.*.json -o /tmp/sum.json
            ./cc-test-reporter upload-coverage -i /tmp/sum.json

  build:
    environment:
      MSBUILD_PROPS: "-p:ContinuousIntegrationBuild=true"
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:3.1
    working_directory: /build
    steps:
      - checkout
      - run:
          name: Install zip
          command: |
            apt-get update -y
            apt-get install -y zip
      - run:
          working_directory: dashboard/src/Piipan.Dashboard
          name: Build Dashboard
          command: dotnet publish $MSBUILD_PROPS -o ./artifacts
      - run:
          working_directory: dashboard/src/Piipan.Dashboard/artifacts
          name: Zip Dashboard build
          command: zip -r dashboard.zip .
      - run:
          name: Move Dashboard zip to persistent directory
          command: |
            mkdir -p workspace
            mv dashboard/src/Piipan.Dashboard/artifacts/dashboard.zip workspace/dashboard.zip
      - persist_to_workspace:
          root: workspace
          paths:
            - dashboard.zip

  deploy:
    executor: azure-cli/azure-docker
    steps:
      - attach_workspace:
          at: /build/workspace
      - azure-cli/login-with-service-principal
      - run:
          name: Upload Dashboard
          command: az webapp deployment source config-zip -g $AZURE_RESOURCE_GROUP -n $APP_NAME --src /build/workspace/dashboard.zip

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
      - build
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: main
