version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.1.0

jobs:
  test:
    environment:
      MSBUILD_PROPS: "-p:ContinuousIntegrationBuild=true"
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:3.1
    steps:
      - checkout
      - run:
          name: Setup Code Climate reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
      - run:
          working_directory: dashboard/tests/Piipan.Dashboard.Tests
          name: Test Dashboard
          command: dotnet test $MSBUILD_PROPS --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=lcov
      - run:
          working_directory: etl/tests/Piipan.Etl.Tests
          name: Test Etl
          command: dotnet test $MSBUILD_PROPS --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=lcov
      - run:
          working_directory: match/tests/Piipan.Match.State.Tests
          name: Test State Match
          command: dotnet test $MSBUILD_PROPS --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=lcov
      - run:
          working_directory: query-tool/tests/Piipan.QueryTool.Tests
          name: Test Query Tool
          command: dotnet test $MSBUILD_PROPS --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=lcov
      - run:
          working_directory: match/tests/Piipan.Match.Orchestrator.Tests
          name: Test Orchestrator Match
          command: dotnet test $MSBUILD_PROPS --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=lcov
      - run:
          working_directory: metrics/tests/Piipan.Metrics.Tests
          name: Test Metrics
          command: dotnet test $MSBUILD_PROPS --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=lcov
      - run:
          working_directory: shared/tests/Piipan.Shared.Tests
          name: Test Shared
          command: dotnet test $MSBUILD_PROPS --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=lcov
      - run:
          name: Upload Code Climate coverage report
          command: |
            ./cc-test-reporter -d format-coverage ./dashboard/tests/Piipan.Dashboard.Tests/TestResults/**/coverage.info --input-type lcov -p /root/project -o /tmp/codeclimate.dashboard.json
            ./cc-test-reporter -d format-coverage ./etl/tests/Piipan.Etl.Tests/TestResults/**/coverage.info --input-type lcov -p /root/project -o /tmp/codeclimate.etl.json
            ./cc-test-reporter -d format-coverage ./match/tests/Piipan.Match.State.Tests/TestResults/**/coverage.info --input-type lcov -p /root/project -o /tmp/codeclimate.match.state.json
            ./cc-test-reporter -d format-coverage ./query-tool/tests/Piipan.QueryTool.Tests/TestResults/**/coverage.info --input-type lcov -p /root/project -o /tmp/codeclimate.query-tool.json
            ./cc-test-reporter -d format-coverage ./match/tests/Piipan.Match.Orchestrator.Tests/TestResults/**/coverage.info --input-type lcov -p /root/project -o /tmp/codeclimate.match.orchestrator.json
            ./cc-test-reporter -d format-coverage ./metrics/tests/Piipan.Metrics.Tests/TestResults/**/coverage.info --input-type lcov -p /root/project -o /tmp/codeclimate.metrics.json
            ./cc-test-reporter -d format-coverage ./shared/tests/Piipan.Shared.Tests/TestResults/**/coverage.info --input-type lcov -p /root/project -o /tmp/codeclimate.shared.json
            ./cc-test-reporter sum-coverage /tmp/codeclimate.*.json -o /tmp/sum.json
            ./cc-test-reporter upload-coverage -i /tmp/sum.json

  build:
    environment:
      MSBUILD_PROPS: "-p:ContinuousIntegrationBuild=true"
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:3.1
    working_directory: /build
    steps:
      - checkout
      - run:
          name: Install zip
          command: |
            apt-get update -y
            apt-get install -y zip
      - run:
          working_directory: dashboard/src/Piipan.Dashboard
          name: Build Dashboard
          command: dotnet publish $MSBUILD_PROPS -o ./artifacts
      - run:
          working_directory: dashboard/src/Piipan.Dashboard/artifacts
          name: Zip Dashboard build
          command: zip -r dashboard.zip .
      - run:
          name: Move Dashboard zip to persistent directory
          command: |
            mkdir -p workspace
            mv dashboard/src/Piipan.Dashboard/artifacts/dashboard.zip workspace/dashboard.zip
      - run:
          working_directory: query-tool/src/Piipan.QueryTool
          name: Build Query Tool
          command: dotnet publish $MSBUILD_PROPS -o ./artifacts
      - run:
          working_directory: query-tool/src/Piipan.QueryTool/artifacts
          name: Zip Query Tool build
          command: zip -r query-tool.zip .
      - run:
          name: Move Query Tool zip to persistent directory
          command: mv query-tool/src/Piipan.QueryTool/artifacts/query-tool.zip workspace/query-tool.zip
      - persist_to_workspace:
          root: workspace
          paths:
            - dashboard.zip
            - query-tool.zip

  deploy:
    executor: azure-cli/azure-docker
    steps:
      - attach_workspace:
          at: /build/workspace
      - azure-cli/login-with-service-principal
      - run:
          name: Upload Dashboard
          command: az webapp deployment source config-zip -g piipan-resources -n piipan-dashboard-xddlt27hoq7hy --src /build/workspace/dashboard.zip
      - run:
          name: Upload Query Tool
          command: az webapp deployment source config-zip -g piipan-resources -n piipan-query-tool-xddlt27hoq7hy --src /build/workspace/query-tool.zip

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
      - build
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: main
