openapi: 3.0.0
info:
  title: "State Matching API"
  version: 1.0.0
  description: "API for detecting a matching PII record within an individual state."
tags:
  - name: "Match"
servers:
  - url: "/v1/"
paths:
  /query:
    post:
      tags:
        - "Match"
      summary: "Search for a matching PII record"
      description: "Queries the state database for a PII record that is an exact match to the full name, date of birth, and social security number in the request body's `query` property."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: object
                  required:
                    - last
                    - dob
                    - ssn
                  properties:
                    first:
                      type: string
                      description: "PII record's first name"
                      example: "Foxtrot"
                    middle:
                      type: string
                      description: "PII record's middle name"
                      example: "Mike"
                    last:
                      type: string
                      description: "PII record's last name"
                      example: "Lima"
                    ssn:
                      type: string
                      description: "PII record's social security    number"
                      pattern: '^\d{3}-\d{2}-\d{4}$'
                      example: "000-12-3456"
                    dob:
                      type: string
                      format: "date"
                      description: "PII record's date of birth"
                      example: "1970-01-01"
      responses:
        '200':
          description: "Matching PII record, if one exists"
          content:
            application/json:
              schema:
                type: object
                properties:
                  match:
                    $ref: '#/components/schemas/PIIRecord'
        '400':
          description: "Bad request. Missing one of the required properties in the request body."
          
components:
  schemas:
    PIIRecord:
      type: "object"
      required:
        - last
        - ssn
        - dob
      properties:
        first:
          type: string
          description: "First name"
          example: "Foxtrot"
        middle:
          type: string
          description: "Middle name"
          example: "Mike"
        last:
          type: string
          description: "Last name"
          example: "Lima"
        ssn:
          type: string
          description: "Social Security number"
          pattern: '^\d{3}-\d{2}-\d{4}$'
          example: "000-12-3456"
        dob:
          type: string
          format: "date"
          description: "Date of birth"
          example: "1970-01-01"
        state:
          type: object
          properties:
            name:
              type: string
              description: "State/territory name"
              example: "Echo Alpha"
            abbr:
              type: string
              description: "Two-letter state/territory postal abbreviation"
              example: "EA"
        exception:
          type: string
          description: "Placeholder for value indicating special processing instructions"
