# Lookup API base spec
openapi: 3.0.0
info:
  title: "Lookup ID Endpoint"
  version: 1.0.0
  description: "API for providing a Lookup ID and receiving the original match data"
servers:
  - url: "/v1"
tags:
  - name: "Lookup"
paths:
  /lookup_ids/{id}:
    $ref: './id.yaml'
