openapi: 3.0.0
info:
  title: "Active Matching API"
  version: 1.0.0
  description: "API for detecting matching PII records across all participating states."
tags:
  - name: "Match"
servers:
  - url: "/v1/"
paths:
  /query:
    post:
      tags:
        - "Match"
      summary: "Search for all matching PII records"
      description: "Queries all state databases for any PII records that are an exact match to the full name, date of birth, and social security number in the request body's `query` property."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  $ref: '#/components/requestBodies/matchQuery'
      responses:
        '200':
          description: "Matching PII records, if any exists"
          content:
            application/json:
              schema:
                type: object
                properties:
                  matches:
                    type: array
                    items:
                      $ref: '#/components/schemas/PIIRecord'
        '400':
          description: "Bad request. Missing one of the required properties in the request body."    

components:
  schemas:
    PIIRecord:
      $ref: '../models/pii-record.yaml'
  requestBodies:
    matchQuery:
      $ref: '../models/match-query.yaml'
