openapi: 3.0.0
info:
  title: "State Matching API"
  version: 1.0.0
  description: "API for detecting a matching PII record within an individual state."
tags:
  - name: "Match"
servers:
  - url: "/v1/"
paths:
  /query:
    post:
      tags:
        - "Match"
      summary: "Search for a matching PII record"
      description: "Queries the state database for a PII record that is an exact match to the full name, date of birth, and social security number in the request body's `query` property."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  $ref: '#/components/requestBodies/matchQuery'
      responses:
        '200':
          description: "Matching PII record, if one exists"
          content:
            application/json:
              schema:
                type: object
                properties:
                  match:
                    $ref: '#/components/schemas/PIIRecord'
        '400':
          description: "Bad request. Missing one of the required properties in the request body."
          
components:
  schemas:
    PIIRecord:
      $ref: '../models/pii-record.yaml'
  requestBodies:
    matchQuery:
      $ref: '../models/match-query.yaml'