# State API base spec
openapi: 3.0.0
info:
  title: "State Matching API"
  version: 1.0.0
  description: "API for detecting matching PII records within an individual state."
tags:
  - name: "Match"
servers:
  - url: "/v1"
security:
  - bearerAuth: []
paths:
  /query:
    post:
      tags:
        - "Match"
      summary: "Search for matching PII records"
      description: "Queries the state database for any PII records that are an exact match to the last name, date of birth, and social security number in the request body's `query` property."
      requestBody:
        $ref: '#/components/requestBodies/MatchQueryRequest'
      responses:
        '200':
          description: "Matching PII records, if any exist"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchQueryResponse'
        '400':
          description: "Bad request. Missing one of the required properties in the request body."
        '401':
          description: "Access token is missing or invalid"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 
  requestBodies:
    MatchQueryRequest:
      $ref: '../schemas/match-query.yaml#/MatchQueryRequest'
  schemas:
    MatchQueryResponse:
      $ref: '../schemas/match-query.yaml#/MatchQueryResponse'
    PiiRecord:
      $ref: '../schemas/pii-record.yaml#/PiiRecord'
